Ft components
memelopez/magicmath pull request #3
Opened 2023-02-18 22:21 UTC by memelopez

## This PR implements: 👨‍💻 🆕 🔥 

- no [linter errors](https://github.com/microverseinc/linters-config) ✅ 
- correct use of [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) ✅ 
- work is documented in a [professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) ✅ 
- follows [JS practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md) ☑️ 
- **deleted all the boilerplate** from CRA ✔️ 
- **created new directory** called `components` ✔️ 
- inside `components`, created a new `Calculator.js` file ✔️ 
- in `Calculator.js`, cerated a react component that matches the design ✔️ 
- implemented **desgin only** ✔️ 
- used **functional** components ✔️ 
- created **1 child component** ✔️ 
- once the `Calculator` was ready, imported it to **be used in top-level component**: `App.js` ✔️ 
- **Tested in browser**, runs without errors ✔️

2023-02-18 22:35 UTC, AmaduKamara reviewed
# Status: Invalid Submission ❌ ❌ ❌

Hi @memelopez,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have the recommended README set up.

- [ ] Kindly use this [README Template](https://github.com/microverseinc/readme-template) for your project and edit its content to match your project and then submit for review 👍🏽

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
```

2023-02-19 02:07 UTC, Reem-lab requested changes
# Hi @memelopez, 👋🏻👋🏻 

Great job so far! 💯🔥♻
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media3.giphy.com/media/SDunHzTgSZbSuQy1EP/giphy.gif"/>

## Highlights
- No Linters erros 💯
- Followed Gitflow ✅
- Great working on the fuctionality ✅
- Descriptive PR 💯


## Required Changes ♻️
_Check the comments under the review._
- [ OPTIONAL ] I think you used for this project typescript frame that's great job for the functionality but I think you should refactor it to javascript since we are studying javascript with react to make sure that you are following best practices for JS 📌✨🚀

![image](https://user-images.githubusercontent.com/58553711/218938431-ad30b816-d427-425e-8902-a6a67d488522.png)

- [ ] I could see that you forget to record a video for the presentation so please recored a video and don't forget to  highlight some interesting piece of code or something you built that you are very proud of.as written in the requirements 🙏🏻♻💯🤩👏🏻👏🏻

![image](https://user-images.githubusercontent.com/58553711/218937493-165b6ccc-2161-4860-8273-e1527f58d587.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-19 02:07 UTC, Reem-lab commented on src/components/Calculator.js
> +  }
- [ ] Great job working so far but I think you missed to make your calculator component as functional component as I can see here it is class based so please make it functional based as required 😊✨🔥🤩
![image](https://user-images.githubusercontent.com/58553711/219908181-4c747c53-7160-4336-b2f2-47d808b7f84c.png)

2023-02-24 04:56 UTC, emmiiorji requested changes
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220870678-4f45b7ed-1d79-4e6a-9338-da59224b2cbc.gif'/>
</div>

You have submitted a project with modified linters configuration. Kindly avoid modifying linter configurations because they represent coding standards that you share with your team.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-24 04:56 UTC, emmiiorji commented on .eslintrc.json
> +    "@typescript-eslint/no-useless-constructor": 0
Please remove the added lines to the `.eslintrc.json` file.

2023-02-24 13:52 UTC, frank1738 reviewed
Hi @memelopez , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [x] Your readme file is missing some important headers like the `key features` and `future features`. Kindly add them to  make your readme file more descriptive

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-02-24 14:17 UTC, memelopez commented
with all due respect, I took out the key features. It's just a calculator that won't even calculate right now... Is it really that important? please, it's the fourth time I've tried to submit this simple project, and 4 times I've been marked as invalid, 1 was understandable (reem-lab's) the other 3 times are nonsense. TWO TIMES HAVE BEEN ABOUT THE README FILEE!!! please.... Im getting kind of annoyed here 😮‍💨

2023-02-24 15:12 UTC, NduatiKagiri requested changes
Hi @memelopez 👋 ,

# CHANGES REQUIRED 💯  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/87394385/221213384-9b0a4957-0996-48cf-beb9-69bf112e20f4.gif)

## Highlights ✔️ 
✅ No Linters errors
✅ Gitflow observed

## Required Changes ♻️

- [ ] Your project has met the requirements and is almost complete. However, for your project to be approved, kindly make the change requested by the previous reviewer and complete adding the `key features` and `future features` headers in your README file to make it more descriptive.

- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 15:12 UTC, NduatiKagiri commented on src/components/Calculator.js
> +// }
- [ ] To make sure that your code is clean, please remove this unused code.

2023-02-24 18:41 UTC, memelopez commented
@frank1738 @NduatiKagiri [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)  is the project requirements for documenting the project in a professional way. It says that I can customize the template to my project. That my project was marked invalid even before to checking the code, shows how you are looking for any pretext to block my progress.

2023-02-24 19:54 UTC, joskalenda commented
> @frank1738 @NduatiKagiri [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) is the project requirements for documenting the project in a professional way. It says that I can customize the template to my project. That my project was marked invalid even before to checking the code, shows how you are looking for any pretext to block my progress.

Hey @memelopez, I have read your comments and I wish to say something about them, first be aware that we do not gain any advantage in blocking your progress, but what we want is to help you understand a good way of working and communicating in a big team. you are the student and we are reviewers, we check again the code you have checked already, and we can't wait to request changes if there is something that is meant to change. it is for your own good.

- [ ] The second point I want to point out is the way you are addressing your opinion, you are in math magician, the 1st weeks at microverse, we have been thought how to interact with other in morning sessions, standup teams, and pair groups, I can feel that `(.  ...)` in your word and it is not good at all, consider this program as work environment, you do not know everything, allow others to help and guide you too, either you know or not, `humility is not an asset`. both reviewers were right, you should ask questions instead of complaining dear @memelopez

2023-02-24 19:56 UTC, joskalenda approved these changes
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @memelopez , 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
| <img src="https://media2.giphy.com/media/2NpKgBuUZtXpu/giphy.gif"/> |

### Highlights
✅ ... Green linters

---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-25 11:40 UTC, merged